/** ابزار ساخت نودهای آزمایشی WBS برای تست‌ها (بدون دادهٔ محرمانه). */
import {
  ControlNodeStatus,
  WbsNodeType,
  WeightSource,
  type NodeComputation,
  type WbsNodeComputedDto,
} from '../api/project-control-types';

export function makeComputation(partial: Partial<NodeComputation> = {}): NodeComputation {
  return {
    isLeaf: true,
    actualProgress: null,
    plannedProgress: null,
    plannedProgressApproximate: false,
    normalizedWeight: null,
    scheduleVariancePercent: null,
    finishVarianceDays: null,
    status: ControlNodeStatus.UNKNOWN,
    bac: null,
    pv: null,
    ev: null,
    ac: null,
    sv: null,
    cv: null,
    spi: null,
    cpi: null,
    isCritical: null,
    totalFloatMinutes: null,
    freeFloatMinutes: null,
    ...partial,
  };
}

export function makeNode(partial: Partial<WbsNodeComputedDto> = {}): WbsNodeComputedDto {
  const id = partial.id ?? Math.random().toString(36).slice(2);
  return {
    id,
    projectId: 'p1',
    controlPlanId: 'plan1',
    parentId: null,
    code: null,
    externalUid: null,
    sourceRow: null,
    sourceFileType: null,
    sourceRawTitle: null,
    title: `نود ${id}`,
    normalizedTitle: `نود ${id}`,
    description: null,
    depth: 0,
    outlineNumber: null,
    materializedPath: id,
    nodeType: WbsNodeType.TASK,
    isSummary: false,
    isMilestone: false,
    isActive: true,
    sortOrder: 0,
    plannedStart: null,
    plannedFinish: null,
    actualStart: null,
    actualFinish: null,
    forecastFinish: null,
    baselineStart: null,
    baselineFinish: null,
    deadline: null,
    plannedDurationMinutes: null,
    actualDurationMinutes: null,
    remainingDurationMinutes: null,
    percentComplete: null,
    physicalProgress: null,
    plannedProgressOverride: null,
    financialProgress: null,
    weight: null,
    weightSource: WeightSource.NONE,
    budgetAmount: null,
    mppCost: null,
    baselineCost: null,
    actualCost: null,
    ownerText: null,
    definitionOfDone: null,
    notes: null,
    statusOverride: null,
    constraintType: null,
    constraintDate: null,
    calendarName: null,
    version: 1,
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
    ...partial,
    computed: makeComputation(partial.computed),
  };
}
